server:
  port: 8181

config:
  txt : 今天天气不错我们约会吧
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wiki
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
