package www.it.yuntu.wiki.entity;

public class MyUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.money
     *
     * @mbggenerated
     */
    private Integer money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.id
     *
     * @return the value of myuser.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.id
     *
     * @param id the value for myuser.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.name
     *
     * @return the value of myuser.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.name
     *
     * @param name the value for myuser.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.password
     *
     * @return the value of myuser.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.password
     *
     * @param password the value for myuser.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.money
     *
     * @return the value of myuser.money
     *
     * @mbggenerated
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.money
     *
     * @param money the value for myuser.money
     *
     * @mbggenerated
     */
    public void setMoney(Integer money) {
        this.money = money;
    }
}